project:
  roots:
    - policy

rules:
  custom:
    missing-metadata:
      level: error
      ignore:
        files:
          - "*_test.rego"
  style:
    line-length:
      level: error
      non-breakable-word-threshold: 80
