name: This is a documented workflow

jobs:
  documented:
    name: This is a documented job
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Nicely documented steps
        run: echo "Something"
      - name: Another nicely documented step
        run: echo "Something else"
