name: Validate via personal conftest policies

'on':
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '12 3 * * 3'

jobs:
  conftest:
    name: Validate via personal conftest policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Validate via personal conftest policies
        uses: docker://openpolicyagent/conftest:latest
        with:
          args: test --all-namespaces .github/workflows
