name: Check and validate Conftest Rego policies

'on':
  push:
    branches:
      - main
  pull_request:

env:
  CONFTEST_VERSION: "0.46.0"
  OPA_VERSION: "0.57.0"

jobs:
  conftest:
    name: Check and validate Conftest Rego policies
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install conftest
        run: |
          mkdir -p "${HOME}/.local/bin"
          curl -sL "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" | tar xzf - -C "${HOME}/.local/bin" conftest
      - name: Install opa
        run: |
          mkdir -p "${HOME}/.local/bin"
          curl -o "${HOME}/.local/bin/opa" -sL "https://github.com/open-policy-agent/opa/releases/download/v${OPA_VERSION}/opa_linux_amd64"
          chmod +x "${HOME}/.local/bin/opa" 
      - name: Setup regal
        uses: StyraInc/setup-regal@v0.1.0
      - name: Checking Rego formatting style
        run: |
          make check-fmt
      - name: Lint conftest policies with regal
        run: |
          make lint
      - name: Unit testing conftest policies
        run: |
          make test
      - name: Ensure that all documentation is updated
        run: |
          make docs
          git status --porcelain | awk '{ print } END { exit (NR > 0) }'
