name: Check Markdown formatting via mdformat

'on':
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '12 3 * * 3'

jobs:
  mdformat:
    name: Check Markdown formatting via mdformat
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install mdformat
        run: |
          pip install mdformat
      - name: Check Markdown formatting via mdformat
        run: |
          mdformat --check .
